### PR TITLE
test-kitchen support

### PR DESCRIPTION
**Pull request by ghost**
You interested in a pull request that adds test-kitchen into the mix? Mostly checking to be sure this isn't something you are already sitting on.

### CODE REVIEW

**Comment by jssjr** [comment]
@gregf Thanks!

**Comment by ghost** [comment]
@jssjr I used the kitchen-docker driver while writing the tests. You might want to switch to the vagrant driver or ec2 driver to get FreeBSD working. Let me know if you have any questions, or need me to make some additional changes.

**Pull request merged**
